# Generated by Django 5.0.6 on 2024-06-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("thumbnail", models.CharField(max_length=255, null=True)),
                ("publication_date", models.DateTimeField()),
                ("media", models.CharField(max_length=255, null=True)),
                ("summary", models.TextField()),
                ("keyword", models.CharField(max_length=255, null=True)),
                (
                    "detail_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.detailcategory",
                    ),
                ),
            ],
        ),
    ]
